#!/usr/bin/env bash
#Install and configure HAProxy

sudo apt update
sudo apt install haproxy -y
haproxy=/etc/default/haproxy
echo "ENABLED=1" | sudo tee -a $haproxy

path=/etc/haproxy/haproxy.cfg
config=\
"
frontend manage_entry
	  bind *:80
	  default_backend my_web_servers
backend my_web_servers
	balance static-rr
	server web-01 52.91.128.189:80 check
	server web-02 54.173.227.35:80 check
"

echo "$config" | sudo tee -a "$path"
sudo systemctl restart haproxy.service
